### ISSUE TITLE
Configureable file formats for auto.sh

### ISSUE THREAD

**Issue by chrisands** [tkareine/chnode#4]
Hi,

For personal projects I use `.node-version` file, but at my work we use **nvm** file format `.nvmrc` to detect node version. It would be nice to be able few file name formats for `auto.sh`.

**Comment by tkareine** [comment]
I added the `CHNODE_AUTO_VERSION_FILENAME` shell variable, which can be used to set the filename for the version files. To use with `.nvmrc` files, set `CHNODE_AUTO_VERSION_FILENAME=.nvmrc`. Details are in the [readme](https://github.com/tkareine/chnode/blob/master/README.md#automatic-version-switching). Would this work for you?

**Comment by chrisands** [comment]
Yes, thank you!
