### ISSUE TITLE
Switch to/Default to system NodeJS

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [tkareine/chnode#7]
Hi,
Amazing tool, thank you!

As a feature request, may you allow switching to system NodeJS and default to that, to replicate chruby featureset?

**Comment by tkareine** [comment]
Hi,


Have you tried `chnode --reset`? It does essentially the same thing as `chruby system`.

Demonstration with `chnode`:

``` bash
ls -l ~/.nodes
# => lrwxr-xr-x    1 tkareine staff   22 Jan  4 14:26 node-18 -> '/usr/local/opt/node@18'/

ls -l /usr/local/bin/node
# => lrwxr-xr-x 1 tkareine staff 32 Jan 21 10:10 /usr/local/bin/node -> ../Cellar/node/19.4.0_1/bin/node*

chnode 18

which node
# => /Users/tkareine/.nodes/node-18/bin/node

node --version
# => v18.13.0

set | grep NODE
# => …
# current Node.js installation path set by chnode:
# => CHNODE_ROOT=/Users/tkareine/.nodes/node-18
# => …

echo "$PATH"
# begins with `$CHNODE_ROOT/bin`:
# => /Users/tkareine/.nodes/node-18/bin:…:/usr/local/bin:/usr/bin:…

chnode --reset

which node
# => /usr/local/bin/node

node --version
# v19.4.0

set | grep NODE
# note that `CHNODE_ROOT` is unset

echo "$PATH"
# does not contain `$CHNODE_ROOT/bin`:
# => …:/usr/local/bin:/usr/bin:…
```

Compare to `chruby`:

``` bash
ls -l ~/.rubies
# => drwxr-xr-x 6 tkareine staff 192 Jan  4 14:36 ruby-3.2.0/

ls -l /usr/bin/ruby
# => -r-xr-xr-x 1 root wheel 167888 Dec  2 10:43 /usr/bin/ruby*

chruby 3.2

which ruby
# => /Users/tkareine/.rubies/ruby-3.2.0/bin/ruby

ruby --version
# => ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin21]

set | grep RUBY
# => …
# => RUBY_ROOT=/Users/tkareine/.rubies/ruby-3.2.0
# => …

echo "$PATH"
# begins with `$RUBY_ROOT/bin`, followed by RubyGems root bin and home bin directories:
# => /Users/tkareine/.gem/ruby/3.2.0/bin:/Users/tkareine/.rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/bin:/Users/tkareine/.rubies/ruby-3.2.0/bin:…:/usr/local/bin:/usr/bin:…

chruby system

which ruby
# => /usr/bin/ruby

ruby --version
# => ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin21]

set | grep RUBY
# note that `CHRUBY_ROOT` is unset

echo "$PATH"
# does not contain `$RUBY_ROOT/bin` and the RubyGems bin directories:
# => …:/usr/local/bin:/usr/bin:…
```

My motivation for using an option like `--reset` instead of the `system` argument for this functionality was that I wanted to dedicate the first argument for selecting the current Node.js version. I felt that the `system` argument would have been an unnecessary special treatment, better handled by an option.

**Comment by Fire-Dragon-DoL** [comment]
> Hi,
> 
> Have you tried `chnode --reset`? It does essentially the same thing as `chruby system`.
> 
> Demonstration with `chnode`:
> 
> ```shell
> ls -l ~/.nodes
> # => lrwxr-xr-x    1 tkareine staff   22 Jan  4 14:26 node-18 -> '/usr/local/opt/node@18'/
> 
> ls -l /usr/local/bin/node
> # => lrwxr-xr-x 1 tkareine staff 32 Jan 21 10:10 /usr/local/bin/node -> ../Cellar/node/19.4.0_1/bin/node*
> 
> chnode 18
> 
> which node
> # => /Users/tkareine/.nodes/node-18/bin/node
> 
> node --version
> # => v18.13.0
> 
> set | grep NODE
> # => …
> # current Node.js installation path set by chnode:
> # => CHNODE_ROOT=/Users/tkareine/.nodes/node-18
> # => …
> 
> echo "$PATH"
> # begins with `$CHNODE_ROOT/bin`:
> # => /Users/tkareine/.nodes/node-18/bin:…:/usr/local/bin:/usr/bin:…
> 
> chnode --reset
> 
> which node
> # => /usr/local/bin/node
> 
> node --version
> # v19.4.0
> 
> set | grep NODE
> # note that `CHNODE_ROOT` is unset
> 
> echo "$PATH"
> # does not contain `$CHNODE_ROOT/bin`:
> # => …:/usr/local/bin:/usr/bin:…
> ```
> 
> Compare to `chruby`:
> 
> ```shell
> ls -l ~/.rubies
> # => drwxr-xr-x 6 tkareine staff 192 Jan  4 14:36 ruby-3.2.0/
> 
> ls -l /usr/bin/ruby
> # => -r-xr-xr-x 1 root wheel 167888 Dec  2 10:43 /usr/bin/ruby*
> 
> chruby 3.2
> 
> which ruby
> # => /Users/tkareine/.rubies/ruby-3.2.0/bin/ruby
> 
> ruby --version
> # => ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin21]
> 
> set | grep RUBY
> # => …
> # => RUBY_ROOT=/Users/tkareine/.rubies/ruby-3.2.0
> # => …
> 
> echo "$PATH"
> # begins with `$RUBY_ROOT/bin`, followed by RubyGems root bin and home bin directories:
> # => /Users/tkareine/.gem/ruby/3.2.0/bin:/Users/tkareine/.rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/bin:/Users/tkareine/.rubies/ruby-3.2.0/bin:…:/usr/local/bin:/usr/bin:…
> 
> chruby system
> 
> which ruby
> # => /usr/bin/ruby
> 
> ruby --version
> # => ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin21]
> 
> set | grep RUBY
> # note that `CHRUBY_ROOT` is unset
> 
> echo "$PATH"
> # does not contain `$RUBY_ROOT/bin` and the RubyGems bin directories:
> # => …:/usr/local/bin:/usr/bin:…
> ```
> 
> My motivation for using an option like `--reset` instead of the `system` argument for this functionality was that I wanted to dedicate the first argument for selecting the current Node.js version. I felt that the `system` argument would have been an unnecessary special treatment, better handled by an option.

That's totally reasonable, I just completely missed the option. Sorry, that's great!
